SET(CMAKE_SWIG_FLAGS)
FIND_PACKAGE(SWIG REQUIRED)
INCLUDE(UseSWIG)

FIND_PACKAGE(Python REQUIRED COMPONENTS Interpreter Development)

SET(PYTHON_PROJECT pycpphello)
foreach(MODULE_NAME IN ITEMS dummy)
  ADD_SUBDIRECTORY(pycpphello/${MODULE_NAME}/python)
ENDFOREACH()
